### ISSUE TITLE
dependency error

### ISSUE THREAD

**Issue by DrChiZhang** [alibaba-yuanjing-aigclab/GeoLRM#3]
Hi thanks for sharing your work. 
I have tried to install you code. 
With "pip install -r requirements.txt", the install huggingface_hub is  0.17.3, exhibiting error of 
"cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub'. 
While after updating huggingface_hub to 0.24.5,  the flash_attn shows the error of "undefined symbol: _ZN3c104cuda9SetDeviceEi". 
Any idea to solve this issue?

**Comment by DrChiZhang** [comment]
I follow this issue https://github.com/Dao-AILab/flash-attention/issues/620
but did not solve my issue.

**Comment by DrChiZhang** [comment]
Hi, I have tried to update nvcc to 12.1, while new error as 
"
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
"
Any idea to solve this issue? thanks

**Comment by DrChiZhang** [comment]
I have similar issue with this issue report https://github.com/michaelfeil/infinity/issues/304#issuecomment-2234477645, 
any solution?

**Comment by Yuxuan-W** [comment]
I faced the same issue and solved.

Here's what I do: after updating huggingface_hub, tokenizers, and transformers. 
1. Delete the build folder and .so file under deform_attn_3d and curope3d folder. Then rebuild them following the instruction.
2. uninstall and reinstall the flash-attn.

Another point is to avoid corruption, I did not use pip -r install requirements/.pt2 when installing sgm. Instead I manually install the required package one by one (not much in my case). Don't know if this helps too.

**Comment by DrChiZhang** [comment]
> I faced the same issue and solved.
> 
> Here's what I do: after updating huggingface_hub, tokenizers, and transformers.
> 
>     1. Delete the build folder and .so file under deform_attn_3d and curope3d folder. Then rebuild them following the instruction.
> 
>     2. uninstall and reinstall the flash-attn.
> 
> 
> Another point is to avoid corruption, I did not use pip -r install requirements/.pt2 when installing sgm. Instead I manually install the required package one by one (not much in my case). Don't know if this helps too.

thanks. 
Seems that flash-attn works for pytorch=2.1.2 & CUDA12.1. 
When I manually instgalled sgm's dependency xformers, pytorch will be updated to new version. 
So "pip install xformers==0.0.23.post1"  works in my case. 

But I have cuda outofmemoryerror issue in my 3090 card. Which GPU card is used in your case?

**Comment by DrChiZhang** [comment]
For ref,  installation in my case

    ```bash
    conda create -n geolrm python=3.10
    conda activate geolrm

    conda install nvidia/label/cuda-12.1.0::cuda-toolkit
    export CUDA_HOME=$CONDA_PREFIX
    conda install pytorch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 pytorch-cuda=12.1 -c pytorch -c nvidia

    pip install flash-attn --no-build-isolation
    pip install -r requirements.txt

    #dependencies for sgm 
    pip install kornia==0.6.9
    pip install xformers==0.0.23.post1
    pip install open-clip-torch
    pip install huggingface-hub==0.23.0
    ``

**Comment by Yuxuan-W** [comment]
> > I faced the same issue and solved.
> > Here's what I do: after updating huggingface_hub, tokenizers, and transformers.
> > ```
> > 1. Delete the build folder and .so file under deform_attn_3d and curope3d folder. Then rebuild them following the instruction.
> > 
> > 2. uninstall and reinstall the flash-attn.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Another point is to avoid corruption, I did not use pip -r install requirements/.pt2 when installing sgm. Instead I manually install the required package one by one (not much in my case). Don't know if this helps too.
> 
> thanks. Seems that flash-attn works for pytorch=2.1.2 & CUDA12.1. When I manually instgalled sgm's dependency xformers, pytorch will be updated to new version. So "pip install xformers==0.0.23.post1" works in my case.
> 
> But I have cuda outofmemoryerror issue in my 3090 card. Which GPU card is used in your case?

I use 48GB A6000. The memory cost for 16k points is around 46GB, but for 8k points is less than 20GB.

**Comment by DrChiZhang** [comment]
> > > I faced the same issue and solved.
> > > Here's what I do: after updating huggingface_hub, tokenizers, and transformers.
> > > ```
> > > 1. Delete the build folder and .so file under deform_attn_3d and curope3d folder. Then rebuild them following the instruction.
> > > 
> > > 2. uninstall and reinstall the flash-attn.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Another point is to avoid corruption, I did not use pip -r install requirements/.pt2 when installing sgm. Instead I manually install the required package one by one (not much in my case). Don't know if this helps too.
> > 
> > 
> > thanks. Seems that flash-attn works for pytorch=2.1.2 & CUDA12.1. When I manually instgalled sgm's dependency xformers, pytorch will be updated to new version. So "pip install xformers==0.0.23.post1" works in my case.
> > But I have cuda outofmemoryerror issue in my 3090 card. Which GPU card is used in your case?
> 
> I use 48GB A6000. The memory cost for 16k points is around 46GB, but for 8k points is less than 20GB.

thanks. 
Seems that 8k points should works for my GPU. 
BTW, how to setup 8k points?

**Comment by Yuxuan-W** [comment]
> > > > I faced the same issue and solved.
> > > > Here's what I do: after updating huggingface_hub, tokenizers, and transformers.
> > > > ```
> > > > 1. Delete the build folder and .so file under deform_attn_3d and curope3d folder. Then rebuild them following the instruction.
> > > > 
> > > > 2. uninstall and reinstall the flash-attn.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Another point is to avoid corruption, I did not use pip -r install requirements/.pt2 when installing sgm. Instead I manually install the required package one by one (not much in my case). Don't know if this helps too.
> > > 
> > > 
> > > thanks. Seems that flash-attn works for pytorch=2.1.2 & CUDA12.1. When I manually instgalled sgm's dependency xformers, pytorch will be updated to new version. So "pip install xformers==0.0.23.post1" works in my case.
> > > But I have cuda outofmemoryerror issue in my 3090 card. Which GPU card is used in your case?
> > 
> > 
> > I use 48GB A6000. The memory cost for 16k points is around 46GB, but for 8k points is less than 20GB.
> 
> thanks. Seems that 8k points should works for my GPU. BTW, how to setup 8k points?

I config that in webui of app.py. Currently I haven't found the corresponding configuration in run_geolrm_sv3d.py.

**Comment by DrChiZhang** [comment]
> > > > > I faced the same issue and solved.
> > > > > Here's what I do: after updating huggingface_hub, tokenizers, and transformers.
> > > > > ```
> > > > > 1. Delete the build folder and .so file under deform_attn_3d and curope3d folder. Then rebuild them following the instruction.
> > > > > 
> > > > > 2. uninstall and reinstall the flash-attn.
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Another point is to avoid corruption, I did not use pip -r install requirements/.pt2 when installing sgm. Instead I manually install the required package one by one (not much in my case). Don't know if this helps too.
> > > > 
> > > > 
> > > > thanks. Seems that flash-attn works for pytorch=2.1.2 & CUDA12.1. When I manually instgalled sgm's dependency xformers, pytorch will be updated to new version. So "pip install xformers==0.0.23.post1" works in my case.
> > > > But I have cuda outofmemoryerror issue in my 3090 card. Which GPU card is used in your case?
> > > 
> > > 
> > > I use 48GB A6000. The memory cost for 16k points is around 46GB, but for 8k points is less than 20GB.
> > 
> > 
> > thanks. Seems that 8k points should works for my GPU. BTW, how to setup 8k points?
> 
> I config that in webui of app.py. Currently I haven't found the corresponding configuration in run_geolrm_sv3d.py.

Would you please specify how to config that in webui? thanks

**Comment by Yuxuan-W** [comment]
> > > > > > I faced the same issue and solved.
> > > > > > Here's what I do: after updating huggingface_hub, tokenizers, and transformers.
> > > > > > ```
> > > > > > 1. Delete the build folder and .so file under deform_attn_3d and curope3d folder. Then rebuild them following the instruction.
> > > > > > 
> > > > > > 2. uninstall and reinstall the flash-attn.
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > Another point is to avoid corruption, I did not use pip -r install requirements/.pt2 when installing sgm. Instead I manually install the required package one by one (not much in my case). Don't know if this helps too.
> > > > > 
> > > > > 
> > > > > thanks. Seems that flash-attn works for pytorch=2.1.2 & CUDA12.1. When I manually instgalled sgm's dependency xformers, pytorch will be updated to new version. So "pip install xformers==0.0.23.post1" works in my case.
> > > > > But I have cuda outofmemoryerror issue in my 3090 card. Which GPU card is used in your case?
> > > > 
> > > > 
> > > > I use 48GB A6000. The memory cost for 16k points is around 46GB, but for 8k points is less than 20GB.
> > > 
> > > 
> > > thanks. Seems that 8k points should works for my GPU. BTW, how to setup 8k points?
> > 
> > 
> > I config that in webui of app.py. Currently I haven't found the corresponding configuration in run_geolrm_sv3d.py.
> 
> Would you please specify how to config that in webui? thanks

just run python app.py and you will see the 'Number of Gaussians' bar.

**Comment by DrChiZhang** [comment]
> > > > > > > I faced the same issue and solved.
> > > > > > > Here's what I do: after updating huggingface_hub, tokenizers, and transformers.
> > > > > > > ```
> > > > > > > 1. Delete the build folder and .so file under deform_attn_3d and curope3d folder. Then rebuild them following the instruction.
> > > > > > > 
> > > > > > > 2. uninstall and reinstall the flash-attn.
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > Another point is to avoid corruption, I did not use pip -r install requirements/.pt2 when installing sgm. Instead I manually install the required package one by one (not much in my case). Don't know if this helps too.
> > > > > > 
> > > > > > 
> > > > > > thanks. Seems that flash-attn works for pytorch=2.1.2 & CUDA12.1. When I manually instgalled sgm's dependency xformers, pytorch will be updated to new version. So "pip install xformers==0.0.23.post1" works in my case.
> > > > > > But I have cuda outofmemoryerror issue in my 3090 card. Which GPU card is used in your case?
> > > > > 
> > > > > 
> > > > > I use 48GB A6000. The memory cost for 16k points is around 46GB, but for 8k points is less than 20GB.
> > > > 
> > > > 
> > > > thanks. Seems that 8k points should works for my GPU. BTW, how to setup 8k points?
> > > 
> > > 
> > > I config that in webui of app.py. Currently I haven't found the corresponding configuration in run_geolrm_sv3d.py.
> > 
> > 
> > Would you please specify how to config that in webui? thanks
> 
> just run python app.py and you will see the 'Number of Gaussians' bar.

Thanks, 
I have changed the 'Number of Gaussians' to 64, still encountered same error.

**Comment by LinShan-Bin** [comment]
1. Many thanks to @DrChiZhang for the dependency solution! 
2. For the 'Number of Gaussians' setting, you can set 'max_seq_length' in the config file 'configs/geolrm.yaml'. This controls the tokens to be processed in the second stage detailed in the paper. Note that one token equals 32 3DGS. (We revised the 'app.py' file to eliminate the confusion of 'token' and '3DGS' in the latest version.)
3. SV3D inference takes a lot of GPU memory. If you encounter the GPU memory problem, try to run SV3D and GeoLRM separately. Firstly, run the 'sv3d_video_sample.py' file, which would cache the SV3D results. Then run the 'run_geolrm.py' file for 3D reconstruction.

**Comment by DrChiZhang** [comment]
> 1. Many thanks to @DrChiZhang for the dependency solution!
> 
>     2. For the 'Number of Gaussians' setting, you can set 'max_seq_length' in the config file 'configs/geolrm.yaml'. This controls the tokens to be processed in the second stage detailed in the paper. Note that one token equals 32 3DGS. (We revised the 'app.py' file to eliminate the confusion of 'token' and '3DGS' in the latest version.)
> 
>     3. SV3D inference takes a lot of GPU memory. If you encounter the GPU memory problem, try to run SV3D and GeoLRM separately. Firstly, run the 'sv3d_video_sample.py' file, which would cache the SV3D results. Then run the 'run_geolrm.py' file for 3D reconstruction.

Thanks for the clarification. 
I will follow your suggestion.

**Comment by DrChiZhang** [comment]
> 1. Many thanks to @DrChiZhang for the dependency solution!
> 
>     2. For the 'Number of Gaussians' setting, you can set 'max_seq_length' in the config file 'configs/geolrm.yaml'. This controls the tokens to be processed in the second stage detailed in the paper. Note that one token equals 32 3DGS. (We revised the 'app.py' file to eliminate the confusion of 'token' and '3DGS' in the latest version.)
> 
>     3. SV3D inference takes a lot of GPU memory. If you encounter the GPU memory problem, try to run SV3D and GeoLRM separately. Firstly, run the 'sv3d_video_sample.py' file, which would cache the SV3D results. Then run the 'run_geolrm.py' file for 3D reconstruction.

I have tried inference sv3d separately, while encountered similar issue. 
Can I use zero123? is there any tutorial of using zere123? I have tried 
"
python run_geolrm_zero123.py configs/geolrm.yaml examples --output_path outputs
"
while, reported the issue of 
"
 File "/home/chi/MyCode/LRM/GeoLRM/run_geolrm_zero123.py", line 83, in <module>
    if os.path.exists(infer_config.unet_path):
  File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key unet_path
    full_key: infer_config.unet_path
    object_type=dict
"
Thanks

**Comment by LinShan-Bin** [comment]
> > 1. Many thanks to @DrChiZhang for the dependency solution!
> >    
> >    2. For the 'Number of Gaussians' setting, you can set 'max_seq_length' in the config file 'configs/geolrm.yaml'. This controls the tokens to be processed in the second stage detailed in the paper. Note that one token equals 32 3DGS. (We revised the 'app.py' file to eliminate the confusion of 'token' and '3DGS' in the latest version.)
> >    3. SV3D inference takes a lot of GPU memory. If you encounter the GPU memory problem, try to run SV3D and GeoLRM separately. Firstly, run the 'sv3d_video_sample.py' file, which would cache the SV3D results. Then run the 'run_geolrm.py' file for 3D reconstruction.
> 
> I have tried inference sv3d separately, while encountered similar issue. Can I use zero123? is there any tutorial of using zere123? I have tried " python run_geolrm_zero123.py configs/geolrm.yaml examples --output_path outputs " while, reported the issue of " File "/home/chi/MyCode/LRM/GeoLRM/run_geolrm_zero123.py", line 83, in if os.path.exists(infer_config.unet_path): File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 355, in **getattr** self._format_and_raise( File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise format_and_raise( File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise _raise(ex, cause) File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise raise ex.with_traceback(sys.exc_info()[2]) # set env var OC_CAUSE=1 for full trace File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in **getattr** return self._get_impl( File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl node = self._get_child( File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child child = self._get_node( File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node raise ConfigKeyError(f"Missing key {key!s}") omegaconf.errors.ConfigAttributeError: Missing key unet_path full_key: infer_config.unet_path object_type=dict " Thanks

For zero123, add a checkpoint path to `configs/geolrm.yaml`:
```yaml
infer_config:
  render_resolution: 1024
  unet_path: ckpts/diffusion_pytorch_model.bin
```

The checkpoint can be downloaded from here: https://huggingface.co/TencentARC/InstantMesh/blob/main/diffusion_pytorch_model.bin

**Comment by DrChiZhang** [comment]
> > > 1. Many thanks to @DrChiZhang for the dependency solution!
> > >    
> > >    2. For the 'Number of Gaussians' setting, you can set 'max_seq_length' in the config file 'configs/geolrm.yaml'. This controls the tokens to be processed in the second stage detailed in the paper. Note that one token equals 32 3DGS. (We revised the 'app.py' file to eliminate the confusion of 'token' and '3DGS' in the latest version.)
> > >    3. SV3D inference takes a lot of GPU memory. If you encounter the GPU memory problem, try to run SV3D and GeoLRM separately. Firstly, run the 'sv3d_video_sample.py' file, which would cache the SV3D results. Then run the 'run_geolrm.py' file for 3D reconstruction.
> > 
> > 
> > I have tried inference sv3d separately, while encountered similar issue. Can I use zero123? is there any tutorial of using zere123? I have tried " python run_geolrm_zero123.py configs/geolrm.yaml examples --output_path outputs " while, reported the issue of " File "/home/chi/MyCode/LRM/GeoLRM/run_geolrm_zero123.py", line 83, in if os.path.exists(infer_config.unet_path): File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 355, in **getattr** self._format_and_raise( File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise format_and_raise( File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise _raise(ex, cause) File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise raise ex.with_traceback(sys.exc_info()[2]) # set env var OC_CAUSE=1 for full trace File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in **getattr** return self._get_impl( File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl node = self._get_child( File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child child = self._get_node( File "/home/chi/MyPrefix/miniconda3/envs/geolrm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node raise ConfigKeyError(f"Missing key {key!s}") omegaconf.errors.ConfigAttributeError: Missing key unet_path full_key: infer_config.unet_path object_type=dict " Thanks
> 
> For zero123, add a checkpoint path to `configs/geolrm.yaml`:
> 
> ```yaml
> infer_config:
>   render_resolution: 1024
>   unet_path: ckpts/diffusion_pytorch_model.bin
> ```
> 
> The checkpoint can be downloaded from here: https://huggingface.co/TencentARC/InstantMesh/blob/main/diffusion_pytorch_model.bin

Thanks a lot. 
I will have a try.

**Comment by DrChiZhang** [comment]
@LinShan-Bin Finally got some results. Thanks for your support. BTW, the training code will be released soon?

**Comment by LinShan-Bin** [comment]
We will release the training code soon. In fact, the code for each training step is already available at https://github.com/alibaba-yuanjing-aigclab/GeoLRM/blob/e8d4d78bd44be800e71946438e4a09b77e433212/src/geolrm_wrapper.py#L231

> @LinShan-Bin Finally got some results. Thanks for your support. BTW, the training code will be released soon?

**Comment by DrChiZhang** [comment]
> We will release the training code soon. In fact, the code for each training step is already available at
> 
> https://github.com/alibaba-yuanjing-aigclab/GeoLRM/blob/e8d4d78bd44be800e71946438e4a09b77e433212/src/geolrm_wrapper.py#L231
> 
> > @LinShan-Bin Finally got some results. Thanks for your support. BTW, the training code will be released soon?

Great. Looking forward to the new update.

**Comment by MichaelWangGo** [comment]
hey, `pip install accelerate==0.31.0` should solve the problem
